language: node_js
node_js:
  - '12'
branches:
  only:
    - master
before_install:
  - npm i -g codecov
install:
  - npm install
script:
  - npm run clean && npm run lint && npm run build && npm test
  - codecov
